
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 18 00:23:21 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int minus = 28;
  public static final int INT = 12;
  public static final int until = 17;
  public static final int CHAR = 13;
  public static final int main = 2;
  public static final int or = 9;
  public static final int constanta = 32;
  public static final int lp = 3;
  public static final int LE = 22;
  public static final int rp = 4;
  public static final int repeat = 16;
  public static final int multiply = 29;
  public static final int equals = 23;
  public static final int divide = 30;
  public static final int TWODOTS = 11;
  public static final int EOF = 0;
  public static final int id = 8;
  public static final int less = 21;
  public static final int lb = 5;
  public static final int assign = 31;
  public static final int greater = 25;
  public static final int error = 1;
  public static final int rb = 6;
  public static final int read = 18;
  public static final int plus = 27;
  public static final int BOOL = 15;
  public static final int write = 19;
  public static final int semi = 10;
  public static final int nequals = 24;
  public static final int REAL = 14;
  public static final int ge = 26;
  public static final int comma = 7;
  public static final int and = 20;
}

